### ISSUE TITLE
Allow prepending file path with "contracts/"

### ISSUE THREAD

**Issue by b-mueller** [tagomaru/truffle-sca2t#21]
Currently truffle-sca2t accepts a contract path from with the "contracts" directory, e.g. in AragonOS, tests for AppProxyBase.sol are generated with:

```
$ truffle run mythx apps/AppProxyBase.sol 
```

From a usability perspective, it would be nice if I could (also) do:

```
$ truffle run mythx contracts/apps/AppProxyBase.sol 
```

That way I can use tab autocompletion and don't need to know the files in advance.

**Comment by tagomaru** [comment]
@b-mueller 
Ah - make sense.
ok I will work on it.

I am working on adding new function, so I will include it into the next release.

**Comment by tagomaru** [comment]
@b-mueller 
Please try v0.3.0

**Comment by b-mueller** [comment]
Works!
